package com.bakeitoff.viewmodel

import android.util.Log
import com.bakeitoff.data.model.RecipeTip
import com.bakeitoff.data.model.Ingredient
import com.bakeitoff.data.model.Recipe
import com.google.gson.Gson

sealed interface RecipeParseResult {
    data class Success(val recipe: Recipe) : RecipeParseResult
    data class Failure(val message: String) : RecipeParseResult
}

object RecipeJsonParser {

    fun parse(rawJson: String?): RecipeParseResult {
        if (rawJson == null) {
            return RecipeParseResult.Failure("Não foi possível extrair a receita dessa mídia.")
        }

        Log.d("BakeItOffDebug", "Tentando fazer parse do JSON...")

        // 1. Find where the JSON starts
        val start = rawJson.indexOf('{')
        if (start == -1) {
            Log.e("BakeItOffDebug", "Texto não possui estrutura JSON.")
            return RecipeParseResult.Failure("A resposta da IA não estava no formato correto.")
        }

        // 2. Brace-tracking algorithm to find the EXACT end
        var openBraces = 0
        var end = -1
        for (i in start until rawJson.length) {
            when (rawJson[i]) {
                '{' -> openBraces++
                '}' -> {
                    openBraces--
                    if (openBraces == 0) {
                        end = i
                        break
                    }
                }
            }
        }

        if (end == -1) {
            Log.e("BakeItOffDebug", "Não encontrou o fechamento da chave.")
            return RecipeParseResult.Failure("A resposta da IA estava incompleta.")
        }

        // 3. If a valid start and end were found, slice it and hand it to Gson
        val cleanJson = rawJson.substring(start, end + 1)
        return try {
            RecipeParseResult.Success(sanitize(Gson().fromJson(cleanJson, Recipe::class.java)))
        } catch (e: Exception) {
            Log.e("BakeItOffDebug", "Erro ao converter o JSON limpo: ${e.message}")
            RecipeParseResult.Failure("A IA não retornou um JSON válido.")
        }
    }

    /**
     * Gson builds objects via reflection and skips the Kotlin constructor — if the AI
     * forgets a key in the JSON, the corresponding field becomes `null` even when the
     * Kotlin type says it can't be, and even when a default value is declared
     * (`= emptyList()`, `= "..."`). The casts to nullable type below are deliberate:
     * without them Kotlin wouldn't even let you write the "?:", but the real value at
     * runtime can genuinely be null.
     *
     * IMPORTANT: every non-null field must be passed here, even ones that "shouldn't"
     * be at risk (e.g. status) — the `.copy()` generated by Kotlin validates as non-null
     * even the default value (`this.status`) of parameters we don't override, and throws
     * a NullPointerException on it even if that default value itself comes back null from Gson.
     */
    fun sanitize(recipe: Recipe): Recipe = recipe.copy(
        title = (recipe.title as String?) ?: "Receita sem título",
        prepTime = (recipe.prepTime as String?) ?: "",
        ingredients = ((recipe.ingredients as List<Ingredient>?) ?: emptyList()).map(::sanitizeIngredient),
        steps = ((recipe.steps as List<String>?) ?: emptyList()).map { (it as String?) ?: "" },
        tags = ((recipe.tags as List<String>?) ?: emptyList()).map { (it as String?) ?: "" },
        videoTips = ((recipe.videoTips as List<RecipeTip>?) ?: emptyList()).map(::sanitizeTip),
        status = (recipe.status as String?) ?: "Não feito"
    )

    // Same Gson-reflection caveat as sanitize() above, one level down: the AI can omit a key
    // on any individual ingredient/tip, not just at the top level of the recipe (this is what
    // actually crashed RecipeTipsSection — a tip missing "fonte" left RecipeTip.source null
    // at runtime despite its non-null Kotlin type).
    private fun sanitizeIngredient(ingredient: Ingredient): Ingredient = ingredient.copy(
        quantity = (ingredient.quantity as String?) ?: "",
        unit = (ingredient.unit as String?) ?: "",
        item = (ingredient.item as String?) ?: ""
    )

    private fun sanitizeTip(tip: RecipeTip): RecipeTip = tip.copy(
        text = (tip.text as String?) ?: "",
        source = (tip.source as String?) ?: "Vídeo"
    )
}
